# Custom RefinedC project file for the examples in the repository.

coq_root = "refinedc-deps"
no_build = false

[cpp]
include = [ "include", "examples/include" ]
use_rc_include = true

[coq]
extra_theories = []
